const res = {
  settings: { fr: "Param", en: "Settings" },
  title: {
    fr: "Théorie musique et pratique",
    en: "Music theory and training",
  },
  retour: { fr: "Retour", en: "Back" },
  notation: { fr: "Notation", en: "Notation" },
  maximalFret: { fr: "Fret maximale demandée", en: "Maximal fret asked" },
  chordsAsked: { fr: "Accords demandés", en: "Asked chords" },
  scalesAsked: { fr: "Gammes demandées", en: "Asked scales" },
  tempo: { fr: "Tempo", en: "Tempo" },
  repetition: { fr: "Répétition chaque mesure", en: "Each bar repetition" },
  chordProgression: {
    fr: "Progression accords joués",
    en: "Chord progression played",
  },
  documentation: { fr: "Doc", en: "Doc" },
  chords: { fr: "Accords", en: "Chords" },
  patterns: { fr: "Patterns", en: "Patterns" },
  gammes: { fr: "Gammes", en: "Scales" },
  intervalles: { fr: "Intervalles", en: "Intervals" },
  questionsAsked: { fr: "Catégories de questions", en: "Questions asked" },
  intervalleDescription: { fr: "Intervalles", en: "Intervals" },
  gammeDescription: { fr: "Notes d'une gamme", en: "Notes in a scale" },
  chordDescription: { fr: "Notes d'un accord", en: "Notes in a chord" },
  quelleNoteSurMancheDescription: {
    fr: "🎸 Quelle est cette note ?",
    en: "🎸 What's this note ?",
  },
  noteSurMancheDescription: { fr: "🎸 Trouvez des ...", en: "🎸 Find some ..." },
  chordsInKeyDescription: { fr: "Accords d'une clé", en: "Chords in a key" },
  nthNoteInKeyDescription: { fr: "Degré dans une clé", en: "Degree in a key" },
  chordsInProgressionDescription: {
    fr: "Progression dans une clé",
    en: "Progression in a key",
  },
  relativeKeyDescription: { fr: "Clé relative", en: "Relative key" },
  strummingQuestionDescription: {
    fr: "🎸 Pratiquez les patterns de strumming",
    en: "🎸 Strumming pattern practice",
  },
  question: { fr: "Nouvelle question", en: "New question" },
  questionSub: {
    fr: "Choisir les types de question posées dans Param",
    en: "Change question types in Settings",
  },
  strumming: { fr: "Strumming", en: "Strumming" },
  clear: { fr: "Vider", en: "Clear" },
  tonique: { fr: "Tonique", en: "Tonic" },
  minorSecond: { fr: "Seconde mineure", en: "Minor second" },
  majorSecond: { fr: "Seconde majeure", en: "Major second" },
  minorThird: { fr: "Tierce mineure", en: "Minor third" },
  majorThird: { fr: "Tierce majeure", en: "Major third" },
  fourth: { fr: "Quarte (juste)", en: "Perfect fourth" },
  dimFifth: { fr: "Quinte dim", en: "Diminished fifth" },
  fifth: { fr: "Quinte", en: "Perfect fifth" },
  minorSixth: { fr: "Sixte mineure", en: "Minor sixth" },
  majorSixth: { fr: "Sixte majeure", en: "Major sixth" },
  minorSeventh: { fr: "Septième mineure", en: "Minor seventh" },
  majorSeventh: { fr: "Septième majeure", en: "Major seventh" },
  octave: { fr: "Octave", en: "Octave" },
  word: { fr: "Mot", en: "Word" },
  letter: { fr: "Lettre", en: "Letter" },
  fr: { fr: "FR", en: "FR" },
  en: { fr: "EN", en: "EN" },
  practice: { fr: "Pratique", en: "Practice" },
  majeur: { fr: "Majeur", en: "Major" },
  mineur: { fr: "Mineur", en: "Minor" },
  chord_m13: { fr: "m13", en: "m13" },
  chord_m9: { fr: "m9", en: "m9" },
  chord_m6: { fr: "m6", en: "m6" },
  chord_m7: { fr: "m7", en: "m7" },
  ionian: { fr: "Majeur (Ionien), I", en: "Major (Ionian), I" },
  dorian: { fr: "Dorien, II", en: "Dorian, II" },
  phrygian: { fr: "Phrygien, III", en: "Phrygian, III" },
  lydian: { fr: "Lydien, IV", en: "Lydian, IV" },
  mixolydian: { fr: "Mixolydien, V", en: "Mixolydian, V" },
  aeolian: { fr: "Mineur Naturel (Éolien), VI", en: "Natural Minor (Aeolian), VI" },
  locrian: { fr: "Locrien, VII", en: "Locrian, VII" },

  harmonicMinor: { fr: "Mineur Harmonique", en: "Harmonic Minor" },
  melodicMinorAsc: { fr: "Mineur Mélodique (Ascendant)", en: "Melodic Minor (Ascending)" },
  melodicMinorDesc: { fr: "Mineur Mélodique (Descendant)", en: "Melodic Minor (Descending)" },

  majorPentatonic: { fr: "Pentatonique Majeure", en: "Major Pentatonic" },
  minorPentatonic: { fr: "Pentatonique Mineure", en: "Minor Pentatonic" },
  blues: { fr: "Blues", en: "Blues" },

  chromatic: { fr: "Chromatique", en: "Chromatic" },
  gamme: {
    fr: (tonique, name) => `Gamme ${name} de ${tonique}`,
    en: (tonique, name) => `${name} scale of ${tonique}`,
  },
  chord: {
    fr: (tonique, name) => `Accord de ${tonique}${name}`,
    en: (tonique, name) => `${tonique}${name} chord`,
  },
  whatIsThisNote: { fr: "Quelle est cette note?", en: "What is this note?" },
  findSome: { fr: "Trouvez des", en: "Find some" },
  clickForAnswer: { fr: "Cliquez pour la réponse", en: "Click for answer" },
  halfTone: { fr: "demi-ton", en: "half-tone" },
  tempo: {
    fr: (bpm, repeats, chords) => `${bpm}bpm, ${repeats}x chaque - ${chords}`,
    en: (bpm, repeats, chords) => `${bpm}bpm, ${repeats}x each - ${chords}`,
  },
  of: { fr: "de", en: "of" },
  fifths: { fr: "Circle of fifths", en: "Circle of fifths" },
  fifthsSub: {
    fr: "Apprendre les accords d'une clé",
    en: "Know chords in keys",
  },
  chordsInTheKey: {
    fr: (key) => `Quels sont les accords de la clé de ${key} ?`,
    en: (key) => `In the key of ${key}, what are the chords ?`,
  },
  nthNoteInKey: {
    fr: (key, roman) => `Quel est l'accord ${roman} dans la clé de ${key} ?`,
    en: (key, roman) => `In the key of ${key}, what is the ${roman} chord ?`,
  },
  relativeKey: {
    fr: (key) => `Quelle est la clé relative mineure de ${key} ?`,
    en: (key) => `What is the relative minor of ${key}?`,
  },
  chordsInProgression: {
    fr: (key, progression) => `Quels sont les accords de la progression ${progression} en ${key} ?`,
    en: (key, progression) => `What are the chords in a ${progression} progression in ${key}?`,
  },
  clickToStart: { fr: "Cliquez pour commencer", en: "Click to start" },
  clickToPause: { fr: "Cliquez pour faire pause", en: "Click to pause" },
  sound: { fr: "Son d'accord", en: "Chord sound" },
  root: { fr: "Unison", en: "Unison" },
  m2: { fr: "Seconde mineure", en: "Minor second" },
  M2: { fr: "Seconde majeure", en: "Major second" },
  m3: { fr: "Tierce mineure", en: "Minor third" },
  M3: { fr: "Tierce majeure", en: "Major third" },
  P4: { fr: "Quarte juste", en: "Perfect fourth" },
  A4: { fr: "Quarte augmentée", en: "Sharp fourth" },
  d5: { fr: "Quinte diminuée", en: "Flat fifth" },
  P5: { fr: "Quinte juste", en: "Perfect fifth" },
  A5: { fr: "Quinte augmentée", en: "Augmented fifth" },
  m6: { fr: "Sixte mineure", en: "Minor sixth" },
  M6: { fr: "Sixte majeure", en: "Major sixth" },
  d7: { fr: "Septième diminuée", en: "Diminished seventh" },
  m7: { fr: "Septième mineure", en: "Minor seventh" },
  M7: { fr: "Septième majeure", en: "Major seventh" },
  P8: { fr: "Octave", en: "Octave" },
  m9: { fr: "Bémol 9", en: "Flat 9" },
  M9: { fr: "9e", en: "9th" },
  s9: { fr: "9e dièse", en: "Sharp 9" },
  P11: { fr: "11e", en: "11th" },
  A11: { fr: "11e augmentée", en: "Sharp 11" },
  m13: { fr: "Bémol 13", en: "Flat 13th" },
  M13: { fr: "13e", en: "13th" },
  rootsAsked: { fr: "Tonique demandée", en: "Roots asked" },
  rythmCategory: { fr: "Strumming", en: "Strumming" },
  rootsExplanation: {
    fr: "* Les toniques non-entourées ont une correspondance enharmonique",
    en: "* Roots without borders have an enharmonic equivalent",
  },
  subtitle: {
    fr: "Bienvenue ! Utilisez ce site pour apprendre et tester vos connaissances musicales. Vous pouvez personnaliser les questions et leur niveau de difficulté dans vos paramètres. Vous pouvez ajouter l'application à votre téléphone pour usage hors-ligne.",
    en: "Welcome! Use this site to learn and test your knowledge of music. You can customize the questions and their difficulty level in your settings. You can add the app to your phone for offline usage.",
  },
  footer: {
    fr: "Créé par <a href='https://vbeaulieu.com'>Vincent Beaulieu</a>. N'hésitez pas à me contacter par email pour partager vos commentaires, expériences d'utilisation et idées !<br>Le code se retrouve sur <a href='https://github.com/stlows/music-theory-trainer'>github</a>. Commentaires peuvent être fait sur ce <a href='https://www.reddit.com/r/musictheory/comments/1kdafbm/made_an_app_to_help_me_learnunderstand_music/'>post reddit</a>.<br/><a href='#' onclick='event.preventDefault();toggleWelcome()'>Message de bienvenue</a>",
    en: "Created by <a href='https://vbeaulieu.com'>Vincent Beaulieu</a>. Feel free to contact me via email to share your feedback, usage experiences, and ideas ! <br>Code is on <a href='https://github.com/stlows/music-theory-trainer'>github</a>. Feedback can be made on this <a href='https://www.reddit.com/r/musictheory/comments/1kdafbm/made_an_app_to_help_me_learnunderstand_music/'>reddit post</a>. <br><a href='#' onclick='event.preventDefault();toggleWelcome()'>Welcome message</a>",
  },
  stats: { fr: "Stats", en: "Stats" },
  clearStats: { fr: "Écraser les statistiques", en: "Clear stats" },
  questionsCount: { fr: "Nombre de résultats", en: "Results count" },
  succesCount: { fr: "Nombre de succès", en: "Success count" },
  succesRatio: { fr: "Pourcentage de succès", en: "Success percentage" },
  timedQuestionCategory: { fr: "Questions chronométrées", en: "Timed questions" },
  autoBad: { fr: "Échec automatique de la question après délai expiré", en: "Fail question automatically after delay" },
  aucun: { fr: "Aucun", en: "None" },
  oui: { fr: "Oui", en: "Yes" },
  non: { fr: "Non", en: "No" },
  replay: { fr: "Rejouer", en: "Replay" },
  whatIsThisInterval: { fr: "Quel est cet intervalle ?", en: "What is this interval ?" },
  intervalByEarDescription: { fr: "👂 Pratiquez vos intervalles à l'oreille", en: "👂 Interval ear training" },
  instrument: { fr: "Instrument (Pratique à l'oreille)", en: "Instrument (Ear training)" },
  guitar: { fr: "Guitare", en: "Guitar" },
  piano: { fr: "Piano", en: "Piano" },
  staff: { fr: "Partition", en: "Staff" },
  piano_staff: { fr: "Piano et partition", en: "Piano and staff" },
  none: { fr: "Aucun", en: "None" },
  selectAll: { fr: "Tout", en: "All" },
  unselectAll: { fr: "Aucun", en: "None" },
  selectAllEnharmonicKeys: { fr: "Uniques", en: "All unique" },
  showNotes: { fr: "Montrez les notes sur l'instrument (intervalles, accords, gammes)", en: "Show notes on the instrument (intervals, chords, scales)" },
  diveIn: { fr: "Allez !", en: "Dive in !" },
  fretboardKnowledge: { fr: "Teste tes connaissances du manche", en: "Test your fretboard knowledge" },
  dontShow: { fr: "Ne plus afficher", en: "Do not show again" },
  chordSimilaritiesDescription: { fr: "🎹 Similarités d'accord (inversions)", en: "🎹 Chord similarities (inversions)" },
  pratiquezLecturePianoDescription: { fr: "🎹 Pratiquez la lecture à vue au piano", en: "🎹 Practice staff sight-reading" },
  pratiquezLecturePiano: { fr: (notesCount, key) => `Jouez ces ${notesCount} notes en ${key}`, en: (notesCount, key) => `Play these ${notesCount} notes in ${key}` },
  readingQuestionsCategory: { fr: "Lecture à vue", en: "Sight-Reading" },
  continuousReading: { fr: "Lecture à vue en continue", en: "Continuous sight-reading" },
  octaves: { fr: "Octaves", en: "Octaves" },
  clefs: { fr: "Clés", en: "Clefs" },
  sameClef: { fr: "Même clé", en: "Same key" },
  differentClef: { fr: "Changer la clé", en: "Change the key" },
  treble: { fr: "Clé de sol", en: "Treble" },
  bass: { fr: "Clé de fa", en: "Bass" },
  resetDefaultSettings: { fr: "Restaurez les paramètres par défaut", en: "Reset to default settings" },
  hidePiano: { fr: "Cacher le piano", en: "Hide piano" },
  beginner: { fr: "débutant", en: "beginner" },
  intermediate: { fr: "intermédiaire", en: "intermediate" },
  advanced: { fr: "avancé", en: "advanced" },
  presets: { fr: "Paramètres enregistrés", en: "Saved settings" },
  afficherCorrection: { fr: "Afficher les boutons d'auto-correction (stats)", en: "Show auto-correct buttons (for stats)" },
  randomPattern: { fr: "Pattern aléatoire", en: "Random pattern" },
  metronome: { fr: "Métronome", en: "Metronome" },
  pianoRythm: { fr: "Jouez ce rythme", en: "Play this rythm" },
  pianoRythmDescription: { fr: "🥁 Pratique de rythme sur la portée", en: "🥁 Rythm practice with notation on the staff" },
  pianoRythmCategory: { fr: "Rythme sur la portée", en: "Rythm on the staff" },
  possibleBeat: { fr: "Séparation possible d'un temps", en: "Possible way to split a beat" },
  practiceTimerCategory: { fr: "Chronomètre de pratique", en: "Practice timer" },
  cancelTimer: { fr: "Terminer la pratique", en: "Finish practice" },
  stopTheBeat: { fr: "Arrêtez le rythme", en: "Stop the beat" },
  startTheBeat: { fr: "Jouez le rythme", en: "Play the beat" },
  octavesDifficulty: { fr: "Difficulté des octaves", en: "Octaves difficulty" },
  easy: { fr: "Facile", en: "Easy" },
  medium: { fr: "Moyen", en: "Medium" },
  hard: { fr: "Difficile", en: "Hard" },
  octavesDifficultyDescriptionEasy: { fr: "Octaves entre C4 et C5 (clé de sol) et entre C3 et C4 (clé de fa)", en: "Octaves between C4 and C5 (treble clef) and between C3 and C4 (bass clef)" },
  octavesDifficultyDescriptionMedium: {
    fr: "Octaves entre G3 et A5 (clé de sol) et entre G2 et D4 (clé de fa)",
    en: "Octaves between G3 and A5 (treble clef) and between G2 and D4 (bass clef)",
  },
  octavesDifficultyDescriptionHard: {
    fr: "Octaves entre F3 et E6 (clé de sol) et entre B2 et E4 (clé de fa)",
    en: "Octaves between F3 and E6 (treble clef) and between B2 and E4 (bass clef)",
  },
  sightReadingStats: { fr: "Stats de lecture à vue", en: "Sight-reading stats" },
  filterByKey: { fr: "Filtrer par tonalité", en: "Filter by key" },
  noStatsYet: {
    fr: "Aucune statistique pour le moment pour cette tonalité. Commencez à pratiquer !",
    en: "No stats yet for this key. Start practicing!",
  },
  note: { fr: "Note", en: "Note" },
  successRate: { fr: "Taux de succès", en: "Success rate" },
  succeeded: { fr: "Succès", en: "Succeeded" },
  tried: { fr: "Essais", en: "Tried" },
  averageTime: { fr: "Temps moyen", en: "Average time" },
  colorDescription: {
    fr: (successRate, avgTime) => `Taux de succès <${Math.round(successRate * 100)}% ou temps moyen >${avgTime}s`,
    en: (successRate, avgTime) => `Success rate <${Math.round(successRate * 100)}% or average time >${avgTime}s`,
  },
  hanonExerciseDescription: { fr: "🎹 Pratiquez les exercices de Hanon au piano", en: "🎹 Practice Hanon exercises on piano" },
  hanonExerciseQuestion: {
    fr: (exercise, key) => `Jouez l'exercice de Hanon #${exercise} en ${key}.`,
    en: (exercise, key) => `Play Hanon Exercice ${exercise.name} in the key of ${key}.`,
  },
  melodyByEarDescription: { fr: "👂 Mélodie à l'oreille", en: "👂 Melody by ear" },
  indice1: { fr: "Révélez la première note", en: "Reveal first note" },
  indice2: { fr: "Révélez les notes utilisées", en: "Reveal used notes" },
  indice3: { fr: "Révélez les notes dans l'ordre", en: "Reveal notes in order" },
  whatIsThisMelody: { fr: "Quelles sont les notes de cette mélodie", en: "Find the notes of this melody" },
  melodyTrainingCategory: { fr: "Mélodie à l'oreille", en: "Melody ear training" },
  melodyTrainingScale: { fr: "Gamme utilisée pour la mélodie à l'oreille", en: "Used scale for melody ear training" },
  melodyTrainingNotesCount: { fr: "Nombre de notes dans la mélodie", en: "Notes count in the melody" },
  melodyScaleMajor: { fr: "Gamme majeure", en: "Major scale" },
  melodyScaleChromatic: { fr: "Gamme chromatique", en: "Chromatic scale" },
  history: { fr: "Historique", en: "History" },
  clearHistory: { fr: "Vider l'historique", en: "Clear history" },
  noHistory: { fr: "Aucun historique", en: "No history" },
  rootPosition: { fr: "Position fondamentale", en: "Root position" },
  firstInversion: { fr: "1ère inversion", en: "1st inversion" },
  secondInversion: { fr: "2ème inversion", en: "2nd inversion" },
  chordChangeDescription: { fr: "Changement d'accord dans toutes les clés", en: "Chord change in all keys" },
  dicteeMusicale: { fr: "Dictée musicale", en: "Musical transcription" },
  showFirstNote: { fr: "Première note de la mesure ", en: "First note of bar " },
  showFullBar: { fr: "Dévoiler la mesure ", en: "Show bar " },
  hideBar: { fr: "Cacher la mesure ", en: "Hide bar " },
  playBars: { fr: "▶️", en: "▶️" },
  stopBars: { fr: "⏹️", en: "⏹️" },
  melodyMaxGapInDegrees: { fr: "Saut maximum d'une note à l'autre", en: "Max gap beetween 2 notes" },
  melodyDegreeLimitHigh: { fr: "Degré le plus élévé possible (de la gamme majeure)", en: "Highest degree possible (of the major key)" },
  melodyDegreeLimitLow: { fr: "Degré le plus bas possible (de la gamme majeure)", en: "Lowest degree possible (of the major key)" },
  melodyAccidentals: { fr: "Altérations sur les notes", en: "Accidentals on the notes" },
  some: { fr: "Un peu (Une note sur huit)", en: "Some (One in eight note)" },
  lots: { fr: "Beaucoup (Une note sur cinq)", en: "Lots (One in five note)" },
  encouragementTitle: { fr: "Tu aimes l'application ?", en: "Enjoying the app ?" },
  encouragementText_1: {
    fr: "Si tu aimes l'application, pense à laisser un pourboire. Ton soutien m'aide à continuer de l'améliorer. Merci et bonne pratique! 🙂",
    en: "If you're enjoying the app, please consider leaving a tip. Your support helps me keep improving it. Thank you and happy practice! 🙂",
  },

  encouragementText_2: {
    fr: "Un petit pourboire fait toute la différence et m'aide à l'améliorer continuellement. 🙂 Merci beaucoup et bonne pratique!",
    en: "A small tip goes a long way and helps support ongoing improvements. 🙂 Thanks so much and happy practice!",
  },

  encouragementText_3: {
    fr: "L'application te plaît ? Gêne-toi pas pour laisser un pourboire 🙂 Ça m'aide à la rendre encore meilleure. Merci et bonne pratique!",
    en: "Like the app? Feel free to leave a tip 🙂 It helps me make it even better. Thanks for your support and happy practice!",
  },

  encouragementText_4: {
    fr: "Ton soutien permet à l'application de continuer d'évoluer. Si tu aimes l'utiliser, pense à laisser un pourboire. Merci et bonne pratique! 🙂",
    en: "Your support keeps the app growing. If you enjoy using it, consider leaving a tip. Thank you and happy practice! 🙂",
  },

  encouragementText_5: {
    fr: "Si l'application t'apporte quelque chose, un pourboire est une belle façon de me soutenir. Ça compte vraiment beaucoup. 🙂 Merci et bonne pratique!",
    en: "If the app brings you value, a tip is a great way to show your support. It truly means a lot. 🙂 Thank you and happy practice!",
  },
  encouragementPaiement: {
    fr: "Virement Interac: vincent_beaulieu@live.ca. Question: Chanson. Réponse: LetItBe",
    en: "Interac e-transfer: vincent_beaulieu@live.ca. Question: Song. Answer: LetItBe"
  },
  last24h: { fr: "Dernières 24h", en: "Last 24h" },
  lastWeek: { fr: "Dernière semaine", en: "Last week" },
  lastMonth: { fr: "Dernier mois", en: "Last month" },
  before: { fr: "Avant", en: "Before" },
  saveCurrentSettings: { fr: "Sauvegarder les paramètres actuels", en: "Save current settings" },
  settingNamePlaceholder: { fr: "Nom du paramétrage", en: "Setting name" },
  delete: { fr: " Supprimer", en: " Delete" },
  system: { fr: "Système", en: "System" },
  user: { fr: "Utilisateur", en: "User" },
  settingsCopiedToClipboard: { fr: "Lien URL avec les paramètres copiés dans le presse-papier", en: "URL link with settings copied to clipboard" },
  importedFromUrl: { fr: "Importé depuis l'URL", en: "Imported from URL" },
  settingsNameConflict: { fr: "Un paramétrage avec ce nom existe déjà. Voulez-vous continuer ?", en: "A setting with this name already exists. Do you want to continue ?" },
  share: { fr: "Partager", en: "Share" },
  deleteConfirmation: { fr: "Êtes-vous sûr de vouloir supprimer ce paramétrage ?", en: "Are you sure you want to delete this setting ?" },
  clearHistoryConfirmation: { fr: "Êtes-vous sûr de vouloir vider l'historique ?", en: "Are you sure you want to clear the history ?" },
  clearStatsConfirmation: { fr: "Êtes-vous sûr de vouloir écraser les statistiques ?", en: "Are you sure you want to clear the stats ?" },
  questionLinkCopiedToClipboard: { fr: "Lien de la question copié dans le presse-papier", en: "Question link copied to clipboard" },
};


function t(key) {
  if (!res[key] || !res[key][settings.lang]) {
    return `${key}`;
  }
  return res[key][settings.lang];
}

function trad() {
  document.querySelectorAll("[data-t]").forEach((x) => {
    if (x.dataset.html === "true") {
      x.innerHTML = t(x.dataset.t);
    } else {
      x.innerText = t(x.dataset.t);
    }
  });
  printAllAccords();
  window.scrollTo(0, 0);
}
