const settingsPresets = {
    piano: {
        beginner: {
            notation: "letter",
            tempo: 60,
            repeats: 2,
            progressionChords: "C",
            plingAtFirstTempo: true,
            accords: ["majeur", "mineur"],
            gammes: ["ionian"],
            lang: "en",
            theme: "light",
            roots: ["C", "G", "D", "A"],
            questions: ["intervalle", "gamme", "chord", "relativeKey", "pratiquezLecturePiano", "pianoRythm"],
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "piano",
            showNotes: "piano",
            continuousReading: "non",
            clefs: ["treble", "bass"],
            octavesDifficulty: "easy",
            afficherCorrection: "false",
            pianoRythm: ['2-Eights', 'Quarter', 'Rest Eight']
        },
        intermediate: {
            notation: "letter",
            tempo: 80,
            repeats: 3,
            progressionChords: "G",
            plingAtFirstTempo: false,
            accords: ["majeur", "mineur", "7", "maj7", "m7", "m(maj7)"],
            gammes: ["ionian", "minorPentatonic", "majorPentatonic"],
            lang: "en",
            theme: "dark",
            roots: ["C", "G", "D", "A", "F"],
            questions: ["intervalle", "gamme", "chord", "chordsInKey", "nthNoteInKey", "chordsInProgression", "relativeKey", "pratiquezLecturePiano", "pianoRythm"],
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "piano",
            showNotes: "piano",
            continuousReading: "non",
            octavesDifficulty: "medium",
            clefs: ["treble", "bass"],
            afficherCorrection: "false",
            pianoRythm: possibleTiming.map(x => x.name).filter(x => !x.includes("Rest"))
        },
        advanced: {
            notation: "letter",
            tempo: 120,
            repeats: 4,
            progressionChords: "Dm",
            plingAtFirstTempo: false,
            accords: [...accords.map(x => x.name)],
            gammes: [...gammes.map(x => x.name)],
            lang: "fr",
            theme: "dark",
            roots: enharmonicKeys,
            questions: ["intervalle", "gamme", "chord", "chordsInKey", "nthNoteInKey", "chordsInProgression", "relativeKey", "chordSimilarities", "pratiquezLecturePiano", "pianoRythm"],
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'false',
            instruments: "piano",
            showNotes: "piano",
            continuousReading: "non",
            clefs: ["treble", "bass"],
            octavesDifficulty: "hard",
            afficherCorrection: "false",
            pianoRythm: possibleTiming.map(x => x.name)
        }
    },
    guitar: {
        beginner: {
            notation: "letter",
            tempo: 60,
            repeats: 2,
            progressionChords: "C",
            plingAtFirstTempo: true,
            accords: ["majeur", "mineur"],
            gammes: ["minorPentatonic", "blues"],
            lang: "en",
            theme: "light",
            roots: ["C", "G", "D", "A", "E"],
            questions: ["intervalle", "gamme", "chord", "relativeKey", "quelleNoteSurManche"],
            frets: 5,
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "guitar",
            showNotes: "guitar",
            continuousReading: "non",
            clefs: ["treble", "bass"],
            octavesDifficulty: "easy",
            afficherCorrection: "false",
            pianoRythm: ['2-Eights', 'Quarter', 'Rest Eight']
        },
        intermediate: {
            notation: "letter",
            tempo: 80,
            repeats: 4,
            progressionChords: "C",
            plingAtFirstTempo: false,
            accords: ["majeur", "mineur", "7", "add9", "sus2", "sus4"],
            gammes: ["ionian", "minorPentatonic", "majorPentatonic", "blues"],
            lang: "en",
            theme: "dark",
            roots: ["C", "G", "D", "A", "F", "E", "B"],
            questions: ["intervalle", "gamme", "chord", "chordsInKey", "nthNoteInKey", "chordsInProgression", "relativeKey", "quelleNoteSurManche", "noteSurManche", "strummingQuestion", "pianoRythm"],
            frets: 7,
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "guitar",
            showNotes: "guitar",
            continuousReading: "non",
            clefs: ["treble", "bass"],
            octavesDifficulty: "medium",
            afficherCorrection: "false",
            pianoRythm: possibleTiming.map(x => x.name).filter(x => !x.includes("Rest") && !x.includes("Triplet"))
        },
        advanced: {
            notation: "letter",
            tempo: 100,
            repeats: 4,
            progressionChords: "C",
            plingAtFirstTempo: false,
            accords: [...accords.map(x => x.name)],
            gammes: [...gammes.map(x => x.name)],
            lang: "fr",
            theme: "dark",
            roots: enharmonicKeys,
            questions: ["intervalle", "gamme", "chord", "chordsInKey", "nthNoteInKey", "chordsInProgression", "relativeKey", "quelleNoteSurManche", "noteSurManche", "strummingQuestion", "pianoRythm"],
            frets: 12,
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'false',
            instruments: "guitar",
            showNotes: "guitar",
            continuousReading: "non",
            clefs: ["treble", "bass"],
            octavesDifficulty: "hard",
            afficherCorrection: "false",
            pianoRythm: possibleTiming.map(x => x.name).filter(x => !x.includes("Triplet"))
        }
    },
}