const settingsPresets = {
    piano: {
        beginner: {
            notation: "letter",
            tempo: 60,
            repeats: 2,
            progressionChords: "C",
            plingAtFirstTempo: true,
            accords: ["majeur", "mineur"],
            gammes: ["majeur"],
            lang: "en",
            theme: "light",
            roots: ["C", "G", "D", "A"],
            questions: ["intervalle", "gamme", "chord", "relativeKey","pratiquezLecturePiano"],
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "piano",
            showNotes: "piano",
            continuousReading: "sameClef",
            clefs: ["treble","bass"],
            octaves: ["0"]
        },
        intermediate: {
            notation: "letter",
            tempo: 80,
            repeats: 3,
            progressionChords: "G",
            plingAtFirstTempo: false,
            accords: ["majeur", "mineur", "7", "maj7", "m7", "m(maj7)"],
            gammes: ["majeur", "minorPentatonic", "majorPentatonic"],
            lang: "en",
            theme: "dark",
            roots: ["C", "G","D", "A","F"],
            questions: ["intervalle", "gamme", "chord", "chordsInKey","nthNoteInKey","chordsInProgression","relativeKey","pratiquezLecturePiano"],
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "piano",
            showNotes: "piano",
            continuousReading: "differentClef",
            clefs: ["treble", "bass"],
            octaves: ["0", "-1"]
        },
        advanced: {
            notation: "letter",
            tempo: 120,
            repeats: 4,
            progressionChords: "Dm",
            plingAtFirstTempo: false,
            accords: [...accords.map(x => x.name)],
            gammes: [...gammes.map(x => x.name)],
            lang: "fr",
            theme: "dark",
            roots: [...fifths.major],
            questions: ["intervalle", "gamme", "chord", "chordsInKey","nthNoteInKey","chordsInProgression","relativeKey","chordSimilarities","pratiquezLecturePiano"],
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'false',
            instruments: "piano",
            showNotes: "piano",
            continuousReading: "differentClef",
            clefs: ["treble", "bass"],
            octaves: ["0", "-1", "1"]
        }
    },
    guitar: {
        beginner: {
            notation: "letter",
            tempo: 60,
            repeats: 2,
            progressionChords: "C",
            plingAtFirstTempo: true,
            accords: ["majeur", "mineur"],
            gammes: ["minorPentatonic"],
            lang: "en",
            theme: "light",
            roots: ["C", "G", "D", "A", "E"],
            questions: ["intervalle", "gamme", "chord", "relativeKey", "quelleNoteSurManche"],
            frets: 5,
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "guitar",
            showNotes: "guitar",
            continuousReading: "sameClef",
            clefs: ["treble","bass"],
            octaves: ["0"]
        },
        intermediate: {
            notation: "letter",
            tempo: 80,
            repeats: 3,
            progressionChords: "G",
            plingAtFirstTempo: false,
            accords: ["majeur", "mineur", "7", "add9", "sus2", "sus4"],
            gammes: ["majeur", "minorPentatonic", "majorPentatonic"],
            lang: "en",
            theme: "dark",
            roots: ["C", "G","D", "A","F", "E","B"],
            questions: ["intervalle", "gamme", "chord", "chordsInKey","nthNoteInKey","chordsInProgression","relativeKey", "quelleNoteSurManche", "noteSurManche"],
            frets: 7,
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'true',
            instruments: "guitar",
            showNotes: "guitar",
            continuousReading: "differentClef",
            clefs: ["treble", "bass"],
            octaves: ["0", "-1"]
        },
        advanced: {
            notation: "letter",
            tempo: 120,
            repeats: 4,
            progressionChords: "Dm",
            plingAtFirstTempo: false,
            accords: [...accords.map(x => x.name)],
            gammes: [...gammes.map(x => x.name)],
            lang: "fr",
            theme: "dark",
            roots: [...fifths.major],
            questions: ["intervalle", "gamme", "chord", "chordsInKey","nthNoteInKey","chordsInProgression","relativeKey", "quelleNoteSurManche", "noteSurManche"],
            frets: 12,
            timerInSeconds: 0,
            autoSelectBadAfterTimer: 'false',
            instruments: "guitar",
            showNotes: "guitar",
            continuousReading: "differentClef",
            clefs: ["treble", "bass"],
            octaves: ["0", "-1", "1"]
        }
    },
};